### ISSUE TITLE
__individual_cookies throws type error

### ISSUE THREAD

**Issue by ifconfig2333** [henryreed/chrome_enum#3]
Traceback (most recent call last):
  File "chrome_enum.py", line 141, in <module>
    class ChromeEnumWindows:
  File "chrome_enum.py", line 304, in ChromeEnumWindows
    def __individual_cookies(self, database_file, key) -> tuple[tuple, list]:
TypeError: 'type' object is not subscriptable

**Comment by henryreed** [comment]
Can you follow up with the following information:
1. Python version
2. OS
3. Running the bundled EXE or your own python environment?
4. Chrome Enum version

From a cursory look it appears you're running an older version of Python that doesn't support tuple typing. Try running this in Python 3.10.4 (or later).

**Comment by ifconfig2333** [comment]
Google modified the decryption algorithm.  can you update it?

**Comment by henryreed** [comment]
> Google modified the decryption algorithm. can you update it?

Is this related to the current issue? Please describe this in more detail. I can confirm on my end that Chrome Enum still works on the latest version of Chrome (103, as the time of writing).

**Comment by ifconfig2333** [comment]
[Python 3.10.6] 
I upgraded the python version. run successfully. Thank you

**Comment by henryreed** [comment]
Glad it worked in the end :)
